[project]
name = "dnd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "attrs>=25.4.0",
    "d20>=1.1.2",
    "json5>=0.12.1",
    "loguru>=0.7.3",
    "pillow>=12.0.0",
    "pydantic>=2.12.4",
    "pyside6==6.10.1",
    "websockets>=15.0.1",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.18.0",
    "taskipy>=1.14.1",
]

[tool.taskipy.tasks]
build = "pyinstaller main.spec --noconfirm"
