[project]
name = "dnd"
version = "1.1.0b3"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=25.1.0",
    "aiohttp>=3.13.3",
    "attrs>=25.4.0",
    "certifi>=2026.1.4",
    "d20>=1.1.2",
    "json5>=0.12.1",
    "packaging>=26.0",
    "pillow>=12.0.0",
    "psygnal>=0.15.1",
    "pydantic>=2.12.4",
    "pyside6==6.10.1",
    "qasync>=0.28.0",
    "requests>=2.32.5",
    "typer>=0.24.1",
    "websockets>=15.0.1",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.19.0",
    "taskipy>=1.14.1",
]


[tool.taskipy.tasks]
build = "task pre-run && pyinstaller scripts/dnd-table.spec --noconfirm"
push-tag = "python scripts/release_helper.py"
pre-run = "uv pip install -e ."
